server {
    listen 80;
    listen [::]:80;

    server_name mysite.local www.mysite.local;

    root /var/www/mysite/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/mysite.access.log;
    error_log  /var/log/nginx/mysite.error.log;
}